// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqnjspzhwrafmzsamcuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxbmpzcHpod3JhZm16c2FtY3VvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyNTIwNDMsImV4cCI6MjA1MzgyODA0M30.ynlk2WwciumpTxzLJZ-jfat3sdrcjTsyyEeSl8ZMkF0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);